### ISSUE TITLE
documentation on which data sets are available

### ISSUE THREAD

**Issue by ofloveandhate** [martinfleis/xyzdata#10]
I noticed that geopandas deprecated `gpd.datasets`.  I'm having trouble finding a source of which sets are available through geodatasets and where to find the strings I use to access them.  Would you consider adding a little tutorial on the documentation page teaching me how to use the library in that regard -- how to find the name of a data set?  Thanks!

**Comment by martinfleis** [comment]
This one is not enough? https://geodatasets.readthedocs.io/en/latest/introduction.html

The whole structure is dictionary-based, so if you want to list all of the available datasets, you can do

```py
geodatasets.data.flatten().keys()
```

**Comment by ofloveandhate** [comment]
Yeah, that's pretty spot-on, thanks.  Would you add a link to that from the github readme landing page?  (The user is smart but lazy, as Hoon Hong taught me.  This is a case of me being lazy and working late at night, and not finding that Introduction page from the github repo).
