### ISSUE TITLE
Inconsistent license metadata

### ISSUE THREAD

**Issue by QuLogic** [martinfleis/xyzdata#18]
When reviewing downstream packaging, my reviewer pointed out that this package is not MIT. And it's true that [`lib.py` says BSD 3-clause](https://github.com/geopandas/geodatasets/blob/main/geodatasets/lib.py#L5), and that [`LICENSE` is BSD 3-Clause](https://github.com/geopandas/geodatasets/blob/main/LICENSE).

But `pyproject.toml` has an MIT classifier:
https://github.com/geopandas/geodatasets/blob/8a9dfa17016973c18a170e6f1fab18f5854a0451/pyproject.toml#L21
and the license metadata is invalid:
https://github.com/geopandas/geodatasets/blob/8a9dfa17016973c18a170e6f1fab18f5854a0451/pyproject.toml#L16

**Comment by martinfleis** [comment]
Sloppy copy&paste on my end. Sorry about that. Will fix and cut a release today.

**Comment by martinfleis** [comment]
Fixed by ce2485b

**Comment by QuLogic** [comment]
Thanks!

**Comment by heshpdx** [comment]
Hi, I noticed that the github license here is BSD-3 which covers the python code in the repository. Are there separate licenses for the data? I notice that at https://geodatasets.readthedocs.io/en/latest/introduction.html, the datasets all indicate the license is `NA`. Are they distributed under the public domain, or something else? Thank you in advance for providing clarity if you can.

**Comment by martinfleis** [comment]
@heshpdx Only GeoDa is NA, the rest has a license assigned. For GeoDa, see https://github.com/geopandas/geodatasets/wiki/NA-licenses-for-GeoDa-datasets.
