### ISSUE TITLE
adding more natural earth datasets?

### ISSUE THREAD

**Issue by rbavery** [martinfleis/xyzdata#19]
can more natural earth datasets be added?
for example:

```
import geopandas as gpd
source_url = ("https://www.naturalearthdata.com/"\
              "http//www.naturalearthdata.com/download/"\
              "10m/cultural/ne_10m_admin_0_countries.zip"
             )
states = gpd.read_file(source_url)
```

the above fails with a `HTTPError: HTTP Error 406: Not Acceptable`

**Comment by martinfleis** [comment]
We have a strict policy of not including any datasets covering contested political boundaries. NE countries would significantly violate that, so there is no chance of including those or any other datasets showing worldwide country boundaries. For some other themes, we can include those here.

FYI, the URL of the countries dataset is different. The file actually lives at `"https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_countries.zip"` and this works:

```py
import geopandas as gpd

path = "https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_countries.zip"
gpd.read_file(path)
```

**Comment by rbavery** [comment]
I see, thank you!
