### ISSUE TITLE
World data with country level information

### ISSUE THREAD

**Issue by acylam** [martinfleis/xyzdata#24]
Hi! I've been trying to plot some country-level statistics using geopandas, and have come across this example, which seems to be exactly what I needed: https://geopandas.org/en/v0.9.0/docs/user_guide/mapping.html

```python
world = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))
world = world[(world.pop_est>0) & (world.name!="Antarctica")]
world['gdp_per_cap'] = world.gdp_md_est / world.pop_est
world.plot(column='gdp_per_cap');
```

![image](https://github.com/user-attachments/assets/c359622f-801a-4c49-b03c-9815ade847fd)

I later realized that this was an old doc and the `'naturalearth_lowres'` dataset is deprecated. I tried to replace with `'naturalearth.land'`, but it does not contain country boundaries (hence, no `name` column). The new doc uses a Chicago map, but I want a world map with country bounds instead: https://geopandas.org/en/v1.0.1/docs/user_guide/mapping.html

```python
chicago = geopandas.read_file(geodatasets.get_path("geoda.chicago_commpop"))
```
![image](https://github.com/user-attachments/assets/9d385f69-8a2c-4410-b3a9-8eb45f1b3e54)

Wondering which dataset I should use to reproduce a similar result as the example in the old doc? FYI, this is what the plot looks like using the new 'naturalearth.land' dataset:

![image](https://github.com/user-attachments/assets/72e8918f-8905-4cf5-a328-5b3587fe4708)

Any help is appreciated, thanks!

**Comment by martinfleis** [comment]
The original `naturalearth_lowres` is this dataset you can download directly from NaturalEarth https://www.naturalearthdata.com/downloads/110m-cultural-vectors/110m-admin-0-countries/. Just be careful about its boundaries as they may reflect a different point of view on contested lands than you're trying to show.

`geodatasets` has a strict policy of not including any data dealing with contested political boundaries, that is why it is not directly included.
